Add automatic update function

diff --git a/files/jenkins-unattended-upgrades b/files/jenkins-unattended-upgrades
--- a/files/jenkins-unattended-upgrades
+++ b/files/jenkins-unattended-upgrades
@@ -1,25 +1,31 @@
 #!/bin/bash
 
 # prepare info file
-INFO_FILE_DIR="/tmp/jenkins-upgrade"
-INFO_FILE="plugins.update.info"
-TOKEN="@/var/lib/jenkins/.administrative-token"
+INFO_FILE_DIR="/usr/share/jenkins"
+TOKEN="/etc/jenkins/admin-password"
+
+if [ -f "$TOKEN" ];then
+    echo "ERROR: no such file $TOKEN"
+    exit 1
+fi
 
 mkdir -p $INFO_FILE_DIR
 # get current version of cli JAR
+
 cd $INFO_FILE_DIR
-rm -f jenkins-cli.jar
-wget http://127.0.0.1:8080/jnlpJars/jenkins-cli.jar
 
-PLUGIN_LIST="$(java -jar jenkins-cli.jar -auth $TOKEN -s http://127.0.0.1:8080/ list-plugins)"
+if ( ! [ -f "jenkins-cli.jar" ] );then
+    unzip -j -o /usr/share/jenkins/jenkins.war WEB-INF/jenkins-cli.jar
+fi
 
-set -x 
+PLUGIN_LIST="$(java -jar jenkins-cli.jar -auth "@${TOKEN}" -s http://127.0.0.1:8080/ list-plugins)"
+
 java -jar jenkins-cli.jar -auth $TOKEN -s http://127.0.0.1:8080/ install-plugin $(echo "$PLUGIN_LIST"|awk '{print $1}'|xargs)
-
 java -jar jenkins-cli.jar -auth $TOKEN -s http://127.0.0.1:8080/ quiet-down -block -timeout 3600000
 apt-get update
 systemctl stop jenkins
 apt-get install jenkins
+unzip -j -o /usr/share/jenkins/jenkins.war WEB-INF/jenkins-cli.jar
 systemctl start jenkins
 
 SUCCESS="false"
